<div class="scrolling cursor-grab"> <span class="font-bold"> EXCHANGE RATES</span><span class="pink">:</span>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;"><span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;"><img
        src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2715%27%20height=%2715%27/%3e" alt="" style="display: block; max-width: 100%; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px;"></span><img data-nimg="intrinsic" src="https://stocks.valyoux.io/public/assets/images/valyoux/ethereum_logo_valyou_x_music.svg"
      srcset="https://stocks.valyoux.io/public/assets/images/valyoux/ethereum_logo_valyou_x_music.svg 1x, https://stocks.valyoux.io/public/assets/images/valyoux/ethereum_logo_valyou_x_music.svg 2x" alt="" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" decoding="async"><noscript></noscript></span>
  <p class="font-[500]">&nbsp;&nbsp;1 ETHEREUM (ETH) &nbsp;=&nbsp;</p>
  <p class="font-[500]">0.02776 BTC</p> &nbsp;=&nbsp; $<p class="font-[500]">1185.89000000 USD</p> &nbsp;&nbsp;<p class="font-[500] text-[#00B8BA]"> + 0.25% </p>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;"><span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;"><img
        src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2715%27%20height=%2715%27/%3e" alt="" aria-hidden="true" style="display: block; max-width: 100%; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px;"></span><img data-nimg="intrinsic" src="https://stocks.valyoux.io/public/assets/images/valyoux/bitcoinlogo.svg"
      srcset="https://stocks.valyoux.io/public/assets/images/valyoux/bitcoinlogo.svg 1x, https://stocks.valyoux.io/public/assets/images/valyoux/bitcoinlogo.svg 2x" alt="" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" decoding="async"><noscript></noscript></span>
  <p class="font-[500]">&nbsp;&nbsp;1 BITCOIN (BTC) &nbsp;=&nbsp;</p>$<p class="font-[500]">20504.84000000 USD</p>
  &nbsp;&nbsp;<p class="text-red font-[500]"> - 0.15% </p>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;"><span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;"><img
        src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2715%27%20height=%2715%27/%3e" alt="" aria-hidden="true" style="display: block; max-width: 100%; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px;"></span><img data-nimg="intrinsic" src="https://stocks.valyoux.io/public/assets/images/valyoux/vuxlogo.svg"
      srcset="https://stocks.valyoux.io/public/assets/images/valyoux/vuxlogo.svg 1x, https://stocks.valyoux.io/public/assets/images/valyoux/vuxlogo.svg 2x" alt="" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" decoding="async"><noscript></noscript></span>
  <p class="font-[500]">&nbsp;&nbsp;1 Valyou X Dollar (VXD) = &nbsp;&nbsp; $</p>
  <p class="font-[500]">1.00090000 USDC</p> &nbsp;&nbsp;<p class="text-red font-[500]"> - 0.1% </p>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;"><span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;"><img
        src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2715%27%20height=%2715%27/%3e" alt="" aria-hidden="true" style="display: block; max-width: 100%; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px;"></span><img data-nimg="intrinsic" src="https://stocks.valyoux.io/public/assets/images/valyoux/vuxlogo.svg"
      srcset="https://stocks.valyoux.io/public/assets/images/valyoux/vuxlogo.svg 1x, https://stocks.valyoux.io/public/assets/images/valyoux/vuxlogo.svg 2x" alt="" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" decoding="async"><noscript></noscript></span>
  <p class="font-[500]">&nbsp;&nbsp;1 VALYOU X MUSIC (VALYOU X) = &nbsp;&nbsp;</p>
  <p class="font-[500]">$0.50 USDC</p> &nbsp;&nbsp;<span style="box-sizing: border-box; display: inline-block; overflow: hidden; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; position: relative; max-width: 100%;"><span style="box-sizing: border-box; display: block; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px; max-width: 100%;"><img
        src="data:image/svg+xml,%3csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20version=%271.1%27%20width=%2750%27%20height=%2750%27/%3e" alt="" aria-hidden="true" style="display: block; max-width: 100%; width: initial; height: initial; background: none; opacity: 1; border: 0px; margin: 0px; padding: 0px;"></span><img data-nimg="intrinsic" srcset="/_next/image?url=%2Fassets%2Fupper_icon.png&amp;w=64&amp;q=75 1x, /_next/image?url=%2Fassets%2Fupper_icon.png&amp;w=128&amp;q=75 2x"
      src="/_next/image?url=%2Fassets%2Fupper_icon.png&amp;w=128&amp;q=75" style="position: absolute; inset: 0px; box-sizing: border-box; padding: 0px; border: none; margin: auto; display: block; width: 0px; height: 0px; min-width: 100%; max-width: 100%; min-height: 100%; max-height: 100%;" decoding="async"></span>
  <p class="font-[500] text-[#00B8BA]"> + 2.5% </p>&nbsp;&nbsp;&nbsp;
</div>
